# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\tsrr.proto\x12\x15\x61\x65\x61.valory.srr.v0_1_0\"\x96\x02\n\nSrrMessage\x12I\n\x07request\x18\x05 \x01(\x0b\x32\x36.aea.valory.srr.v0_1_0.SrrMessage.Request_PerformativeH\x00\x12K\n\x08response\x18\x06 \x01(\x0b\x32\x37.aea.valory.srr.v0_1_0.SrrMessage.Response_PerformativeH\x00\x1a'\n\x14Request_Performative\x12\x0f\n\x07payload\x18\x01 \x01(\t\x1a\x37\n\x15Response_Performative\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x42\x0e\n\x0cperformativeb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "srr_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_SRRMESSAGE"]._serialized_start = 37
    _globals["_SRRMESSAGE"]._serialized_end = 315
    _globals["_SRRMESSAGE_REQUEST_PERFORMATIVE"]._serialized_start = 203
    _globals["_SRRMESSAGE_REQUEST_PERFORMATIVE"]._serialized_end = 242
    _globals["_SRRMESSAGE_RESPONSE_PERFORMATIVE"]._serialized_start = 244
    _globals["_SRRMESSAGE_RESPONSE_PERFORMATIVE"]._serialized_end = 299
# @@protoc_insertion_point(module_scope)
